GUILD_ID: 0 #ID of your server
LOG_ID: 0 #Log stuff to that channel
VERIFY_ID: 0 #Verification channel
VERIFY_CHNL_MESSAGE: "By reacting with ✅ you agree that you have read and understand the rules.\nBreaking these rules will result in punishments or even permament bans."

tokens:
  bot: "YOUR_BOT_TOKEN_HERE" #Token used to run bot, do NOT share it. If leaked anyone can take control of the bot and cause irreversible damage
  yt: "YOUR_YT_TOKEN_HERE" #Token used to check for yt uploads, also do NOT share.

systems:
  filter: true #Filtering system
  leveling: true #Leveling system
  yt: true #Youtube monitoring
  welcome: true #Welcome members
  
behaviour:
  COMMAND_PREFIX: "!" #Here what you set will trigger the bot to check for command (for example !clear)
  filter:
    DETECTION_THRESHOLD: 85 #The higher, the less will filter detect/flag. Reccomended between 80 to 90
  flags:
    CAN_FLAG_ADMINS: false #If on admins can get flagged and punished
    FILTER_AFFECTS_ADMINS: false #If on filter will also prevent admins from sending blacklisted words as well as punish them
    MUTE_TIME: 900 #Mute after filter detection in s
    WARN_DM: "You have been warned for saying: `{word}`.\nIf you think you have been mistakenly flagged please react to this message with ⚠️ within 24 hours."
    FLAG_LIMIT: 10 #When user reaches that number of flags they will get instantly banned
    review_channel:  #Channel where review requests get sent

roles:
  verified_ID: 0 #ID for verified role
  lockdown_ID: 0 #ID for lockdown role
  mod_ID: 0 #ID for mod role
  bot_manager_ID: 0 #Can do certain commands

LEVELING:
  BASE_XP: 20
  SCALE_FACTOR: 2
  CHANNEL_ID: 0 #where to send level up messages
  EMBED:
    title: "Level up!"
    description: " has reached a new level!"
    field: "Progress"

WELCOME:
  WELCOME_CHANNEL_ID: 0 #Where will the bot send greetings
  WELCOME_MESSAGE: "{user} joined"
  GOODBYE_MESSAGE: "{user} left"
  "SHOW_CARD_ON_ENTER": true #When user joins, bot will send a banner
  "SHOW_CARD_ON_LEAVE": true #When user leaves, bot will send a banner

youtube:
  target: "https://www.youtube.com/channel/CHANNEL_ID_HERE" #Link to yt channel
  announcements:
    new_video: "{PING_everyone} ... has posted a new [video]({target_video_link})!\n**# {title}**\n`{description}`"
    new_short: "{PING_everyone} ... has posted a new [short]({target_video_link})!\n**# {title}**\n`{description}`"
    upcoming_premiere: "{PING_everyone} ... has set a [premiere]({target_video_link})!\n**# {title}**\nPremiere on **{premiere_date}**\n\n`{description}`"
    premiere: "{PING_everyone} ... is premiering [now]({target_video_link})!\n**# {title}**\n\n`{description}`"
    upcoming_stream: "{PING_everyone} ... has set a [stream]({target_video_link})!\n**# {title}**\non **{premiere_date}**\n\n`{description}`"
    stream: "{PING_everyone} ... is currently [streaming]({target_video_link})!\n**# {title}**\n`{description}`"
    new_post: "{PING_everyone} ... has made a new [post]({target_video_link})!\n**# {title}**\n{image}"

  flags:
    IGNORE_SHORTS: false
    IGNORE_VIDEOS: false
    IGNORE_STREAMS: false
    IGNORE_POSTS: true #Posts checking does not work in this version
    CHECK_INTERVAL: 30 #Check for new uploads every CHECK_INTERVAL s
    ANNOUNCEMENT_CHANNEL_ID: "" #Channel where bot will announce uploads

watchdog:
  restart_delay: 0 #Unused for now
  check_interval: 30 #How often to check system's status

ICONS: # Make sure bot can access these
  icon_warn: ""
  icon_mute: ""
  icon_kick: ""
  icon_ban: ""
  icon_clear: ""
  icon_adjust: ""
  icon_info: ""
  icon_fail: ""